version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      npm-runtime:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /server
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      relay-python:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /server
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
